### ISSUE TITLE
How to handle different URLs

### ISSUE THREAD

**Issue by anshulix** [firebase/quickstart-nodejs#1]
I've a situation, having multiple users, all of them have unique hashId assigned to them, which make their URL different. While my client side updates the data in firebase, I need to apply server interactions to the child_added. 

App can have any number of users, how to scale child_added? As reference to every URL is new, I'm not sure of this situation, new to firebase.

**Comment by anshulix** [comment]
I got the solution. Thanks

**Comment by nicolasgarnier** [comment]
Glad you found out @anshulix
