### ISSUE TITLE
Firebase 3.0

### ISSUE THREAD

**Issue by lauramorinigo** [firebase/quickstart-nodejs#10]
Allo! Could you please update this to firebase 3? I mean use firebase-admin instead of firebase:
var firebase = require('firebase-admin');
firebase.initializeApp({
  credential: firebase.credential.cert(serviceAccount),
  databaseURL:"https://URL.firebaseio.com"
})

In firebase official page the update is already did :)
Thanks,
Laura

**Comment by nicolasgarnier** [comment]
Definitely :) I'll work on this soon!

**Comment by dwberry** [comment]
Sent a PR on this very issue...
