### ISSUE TITLE
Rulecoverage url not working

### ISSUE THREAD

**Issue by ESBA-salman** [firebase/quickstart-nodejs#103]
Hi,

The tests are running fine. However the rulecoverage url does not work

View rule coverage information at http://localhost:8080/emulator/v1/projects/<projectname-redacted>:ruleCoverage.html

However when I click on the link I see the following text

Not found.

Any idea how to make it work? 

Emulator is still running in the background.

Thanks

**Comment by ryanpbrewster** [comment]
That URL usually has a project id in it, like
http://localhost:8080/emulator/v1/projects/ryan-test:ruleCoverage.html

**Comment by ESBA-salman** [comment]
> That URL usually has a project id in it, like
> http://localhost:8080/emulator/v1/projects/ryan-test:ruleCoverage.html

Yes, I did not put it here.

Here is what my test spits out. 
http://localhost:8080/emulator/v1/projects/myproject:ruleCoverage.html

**Comment by ryanpbrewster** [comment]
Yep, definitely seems broken. Looking at older versions to see when it broke.

**Comment by ESBA-salman** [comment]
> Yep, definitely seems broken. Looking at older versions to see when it broke.

Thank you! Let me know if you are able to find a particular version which has the rulecoverage working.

**Comment by ryanpbrewster** [comment]
Identified the underlying issue.

The browser SDK sometimes sends requests with `Content-Type: text/plain`. In v1.9.0 we added suport for the browser SDK, so we automatically convert all `text/plain` requests into `application/json` requests. Unfortunately, this breaks the rule coverage report.

Fix in progress. Thanks for reporting this :)

**Comment by khyveasna** [comment]
khyveasna111@gmail.com

**Comment by ESBA-salman** [comment]
Hi @ryanpbrewster ,

Is there a way for a test to tell us that you have an object in DB but you have no tests against it?

**Comment by ryanpbrewster** [comment]
In general, no.

Can you clarify what kind of tracking you're looking for? For instance, any object in the database has been created, so every object will have exercised security rules. For my own security rules, I usually shoot for every _rule_ having at least two requests, one that succeeds and one that fails. I don't usually enforce that every _object_ has a test.

However, you can programmatically enforce this in your test logic by:
  - keeping track of DB objects that you issue tests against
  - at the end, read the entire database and check to see if there are any objects there that haven't been tested
