### ISSUE TITLE
Should the firestore/browser-quickstart example point to port 8081 instead of 8080?

### ISSUE THREAD

**Issue by hrgui** [firebase/quickstart-nodejs#104]
Should this example point to port 8081 instead of 8080, or is this correct?
https://github.com/firebase/quickstart-nodejs/blob/master/firestore-emulator/browser-quickstart/public/index.html#L16

I found that when pointing to port 8081,  the example no longer errors out on the `channel?` request.

**Comment by samtstern** [comment]
@hrgui what version of the `firebase` CLI are you using?  As of version `7.5.0` and higher we prefer port `8080` for webchannel traffic to the emulator:
https://github.com/firebase/firebase-tools/releases/tag/v7.5.0

**Comment by hrgui** [comment]
Ah, I'm using v7.3.0. I'll update to v7.5.0+.

Should there be a min version requirement in the readme for `browser-quickstart`?

**Comment by samtstern** [comment]
@hrgui good idea!  Addressed here:
https://github.com/firebase/quickstart-nodejs/commit/661cf51b206b49a7397bcffb805cd7353fc42b77
