### ISSUE TITLE
Cannnot install on windows 10

### ISSUE THREAD

**Issue by awesomesk1ll** [firebase/quickstart-nodejs#123]
Hi, there is something happens wrong when i trying to start/setup **auth-sessions** demo.
Cloning seems is ok:
```
C:\>git clone https://github.com/firebase/quickstart-nodejs
Cloning into 'quickstart-nodejs'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
Receiving objects:  97% (1363/1405)d 3 (delta 0), pack-reused 1398Receiving objects:  96% (1349/1405)
Receiving objects: 100% (1405/1405), 474.43 KiB | 1.43 MiB/s, done.
Resolving deltas: 100% (730/730), done.
```
Here is my node/npm versions, in readme written Node.js (>= 6.0.0) is needed for start.
```
C:\quickstart-nodejs\auth-sessions>node -v
v12.16.0
C:\quickstart-nodejs\auth-sessions>npm -v
6.13.4
```
And there is my debug.log when i used command **npm install**
https://yadi.sk/d/ebmhXcaJX251Gg

My question is simple: **How to get them work ?**

**Comment by awesomesk1ll** [comment]
got them work with strong versions in dependencies.
https://yadi.sk/d/RbpbOvMxPy7nLQ

**Comment by samtstern** [comment]
@awesomesk1ll in that `package.json` you're using some very old versions of Firebase dependencies, multiple major versions old.

I would suggest:
  * Upgrading as far as possible
  * Using Node 8+

If you still have issues after that we can take a look

**Comment by awesomesk1ll** [comment]
ReRear my first post. Node 12
