### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by cdstamper** [firebase/quickstart-nodejs#13]
Great sample project! However it seems like it's intended for hosting and execution on Firebase.

Would it be possible to update Readme.md with simple instructions on how to deploy as firebase project?

**Comment by jaydev1997** [comment]
@cdstamper If you want to run locally, you need to install dependencies first see -->  https://www.firebase.com/docs/hosting/command-line-tool.html  then inside directory where firebase.json located open command line and run server with ```firebase serve```

**Comment by shaychoo** [comment]
This isn't a firebase project.
this sample ment to be  deployed on nodejs server and used as a server side for calculations or some server side logic.

**Comment by samtstern** [comment]
This is an old issue so I am going to close it, @shaychoo gave the correct answer anyway.  Thanks!
