### ISSUE TITLE
Is there anyway to get access token without firebase-admin

### ISSUE THREAD

**Issue by huy-lv** [firebase/quickstart-nodejs#145]
Hello, i want to get access token to call REST API get remote config. Is there anyway to get access token without `firebase-admin` because we can not use `firebase-admin` in react native :D

**Comment by samtstern** [comment]
@huy-lv this is working as intended.  The Remote Config admin API is meant to be used from trusted (server) environments only.  It's not safe to put admin credentials in React Native.

If you want to use Remote Config client APIs in your RN app see these instructions:
https://rnfirebase.io/remote-config/usage

**Comment by huy-lv** [comment]
hey @samedson , i can not use that lib because i use Expo framework, `@react-native-firebase/app` does not include in expo. Please help me find a way to generate access token so i can get remote config through REST API instead of some lib else.
