### ISSUE TITLE
Connect using firebase rather than firebase-admin?

### ISSUE THREAD

**Issue by vkarpov15** [firebase/quickstart-nodejs#15]
The docs tell me to use the client JS SDK for end-user access:

![image](https://cloud.githubusercontent.com/assets/1620265/24973672/ddbc6b84-1f7c-11e7-90ba-7a115684bc0b.png)

But there's no examples for how to do this with nodejs.

**Comment by kleinfreund** [comment]
I believe this section is supposed to cover that: https://firebase.google.com/docs/web/setup#add_firebase_to_your_app

In particular:

```
// Initialize Firebase
// TODO: Replace with your project's customized code snippet
var config = {
  apiKey: "<API_KEY>",
  authDomain: "<PROJECT_ID>.firebaseapp.com",
  databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
  storageBucket: "<BUCKET>.appspot.com",
};
firebase.initializeApp(config);
```

Though I have no idea what a `storageBucket` is.

**Comment by nicolasgarnier** [comment]
Yup there are not really anything differences in using the JS sdk ou in Node vs Web. The only difference is in the install and import.

Install the SDK with: `npm install --save firebase`
Import the SDK with: `var firebase = require('firebase');`
