### ISSUE TITLE
serviceAccountKey.json example

### ISSUE THREAD

**Issue by djom20** [firebase/quickstart-nodejs#16]
Amazing sample project, thanks to you for it!

Would it be possible to add a serviceAccountKey.json example? I would like know what is the file structure.

**Comment by samtstern** [comment]
@djom20

**Comment by djom20** [comment]
Other question about that. How do you to upload this file if isn't in the repository?

**Comment by samtstern** [comment]
@djom20 see this question for the answer:
http://stackoverflow.com/questions/31715261/reading-secret-config-file-on-heroku-without-using-env-vars

Going to close this issue since it's now just about Heroku.
