### ISSUE TITLE
A suggestion for writing README.md

### ISSUE THREAD

**Issue by Andrewyg** [firebase/quickstart-nodejs#17]
I found out it'll be nice if the index.js link text can bring you to the exact line to modify when you click on it rather than just bring you to the code page

How to fix:

For example I'm bringing you to line 39 of index.js in the database directory add "#L39" at the bottom of the URL 
Eg. https://github.com/firebase/quickstart-nodejs/blob/master/database/index.js#L39

**Comment by Andrewyg** [comment]
Oops I paste the wrong URL
Here is the right one

https://github.com/firebase/quickstart-nodejs/blob/master/database/index.js#L39

**Comment by morganchen12** [comment]
Hey @Andrewyg,

There don't seem to be any links to source files in README.md. Are you referencing some other document?
