### ISSUE TITLE
Is there a way to use 'message.ack()' in pub/sub?

### ISSUE THREAD

**Issue by grandmore** [firebase/quickstart-nodejs#18]
Is there a way to force a message RETRY by NOT acknowledging?

The normal google [pub/sub node.js library](https://cloud.google.com/pubsub/docs/quickstart-client-libraries#pubsub-client-libraries-nodejs) has.

```
// "Ack" (acknowledge receipt of) the message
  message.ack();
```
If there is an error I want to notify the issue but NOT loose the published message.

**Comment by samtstern** [comment]
@grandmore this repository is for the Firebase Node.js libraries, so please ask Cloud PubSub quesitons on a more appropriate forum (maybe StackOverflow?)
