### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by hram** [firebase/quickstart-nodejs#27]
I have an error when run `node index.js common-message`

> (node:2440) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'auth' of undefined
>     at C:\ggggg\quickstart-nodejs\messaging\index.js:25:32
>     at new Promise (<anonymous>)
>     at getAccessToken (C:\ggggg\quickstart-nodejs\messaging\index.js:23:10)
>     at sendFcmMessage (C:\ggggg\quickstart-nodejs\messaging\index.js:49:3)
>     at Object.<anonymous> (C:\ggggg\quickstart-nodejs\messaging\index.js:130:3)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
> (node:2440) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
> (node:2440) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rajasimon** [comment]
After googling I solved it by upgrading to `"googleapis": "^27.0.0"`

**Comment by samtstern** [comment]
Thanks @rajasimon!  Closing old issue which appears to have a solution.
