### ISSUE TITLE
How to send push notification to more than 10000 users using firebase in nodejs?

### ISSUE THREAD

**Issue by PhanHaHus** [firebase/quickstart-nodejs#30]
If I have more than 10k user, and I have an array of token, how can I send to all of user ? I tried to chunk array 1000 user each time, push 1000 user to a Topic, and remove the user from a topic ( in a loop). But it is running false. Does anyone meet this case? thank you!
Sample code:

    let registrationTokens =[
    token1,
    token2,...
    token10000
    ]
    let promises = [];
    
    for (let i = 0; i < 10; i++) {
        promises.push(
            admin
                .messaging()
                .subscribeToTopic(registrationTokens, topic) // subscrible topic 
                .then(function(response) {
                    // send message to topic
                    admin
                        .messaging()
                        .send(message)
                        .then(response => {
                            // remove user from topic 
                            admin
                                .messaging()
                                .unsubscribeFromTopic(registrationTokens, topic);
                        })
                        .catch(error => {
                            console.log('Error sending message:', error);
                        });
                })
                .catch(function(error) {
                    console.log('Error subscribing to topic:', error);
                    console.log(error);
                    return res.send(error);
                })
        );
    }
    
    Promise.all(promises);

**Comment by anonystick** [comment]
You should add each 1k to a topic and use it send it. Notes: Each topic limit 1k regis token!

**Comment by ryanpbrewster** [comment]
I think asking this question on StackOverflow or filing a ticket with Firebase Support will give better responses for this kind of question. Closing out this issue as it's not directly related to the quickstarts.
