### ISSUE TITLE
database-emulator/javascript-quickstart open-sesame command not working

### ISSUE THREAD

**Issue by FeynmanDNA** [firebase/quickstart-nodejs#40]
The current README for the javascript-quickstart of the database-emulator is instructing users to initialize with two commands, however the `--open-sesame` command is not working.
![image](https://user-images.githubusercontent.com/26617036/49058181-da0cd100-f23d-11e8-9864-649476b7b961.png)

**Error message in the command line**:
```
firebase --open-sesame emulators
Error: Did not recognize preview feature 
```

**Comment by samtstern** [comment]
@FeynmanDNA are you running the latest version of the firebase CLI?

**Comment by FeynmanDNA** [comment]
@samtstern hi! I checked my firebase version just now it is:
```
$firebase --version
6.1.1
```

**Comment by ryanpbrewster** [comment]
Good catch! This is a documentation issue, the most recent version of the CLI tool no longer requires `--open-sesame`. https://github.com/firebase/quickstart-nodejs/pull/42 should fix this.

**Comment by FeynmanDNA** [comment]
@ryanpbrewster glad to help!
