### ISSUE TITLE
database-emulator/javascript-quickstart no need to have firebase.json to serve database?

### ISSUE THREAD

**Issue by FeynmanDNA** [firebase/quickstart-nodejs#41]
To launch the quickstart example in the database-emulator with `firebase setup:emulators:database && firebase serve --only database`. And it looks like the `firebase.json` has no effect on the emulator? I removed the firebase.json, and the firebase setup and serve still works. 

I am curious to learn if firebase.json is not doing anything for the database-emulator to work?

**Comment by samtstern** [comment]
@FeynmanDNA what behavior did you expect?  Specifically, what effect did you expect `firebase.json` to have on the Realtime Database emulator?

**Comment by FeynmanDNA** [comment]
@samtstern hi! Thanks for the communication!

I am very new to firebase myself, and I thought `firebase.json` is required to deploy assets with the Firebase CLI? 

So maybe since we are not deploying, only `serving` or `emulating`, we do not need a `firebase,json` file?

The example files in the quickstart folder did provide a `firebase.json`, and by removing it the project is not affected. So that was the confusing part for me.

**Comment by ryanpbrewster** [comment]
The `firebase.json` is not strictly necessary, but most real-world Firebase applications will need one --- it becomes important as soon as you want to do anything besides test your application, like deploying it!

**Comment by ryanpbrewster** [comment]
Please feel free to re-open if you can think of some way to make this more intuitive for other developers. Maybe add a note to the README?
