### ISSUE TITLE
Not working when http_proxy had set in system's environment variable

### ISSUE THREAD

**Issue by ittechsathish** [firebase/quickstart-nodejs#44]

**Comment by ittechsathish** [comment]
C:\devcontrolpanel-m\rules-test (master -> origin) (cloud-firestore-emulator-typescript-quickstart@1.0.1)
λ npm test

> cloud-firestore-emulator-typescript-quickstart@1.0.1 pretest C:\devcontrolpanel-m\rules-test
> tsc


> cloud-firestore-emulator-typescript-quickstart@1.0.1 test C:\devcontrolpanel-m\rules-test
> set FIREBASE_FIRESTORE_EMULATOR_ADDRESS='http://localhost:8080' &&mocha



(node:1572) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
  MyApp
    1) "before each" hook for "require users to log in before creating a profile"


  0 passing (556ms)
  1 failing

  1) MyApp
       "before each" hook for "require users to log in before creating a profile":
     Error: 14 UNAVAILABLE: Connect Failed
      at Object.exports.createStatusError (node_modules\grpc\src\common.js:87:15)
      at Object.onReceiveStatus (node_modules\grpc\src\client_interceptors.js:1188:28)
      at InterceptingListener._callNext (node_modules\grpc\src\client_interceptors.js:564:42)
      at InterceptingListener.onReceiveStatus (node_modules\grpc\src\client_interceptors.js:614:8)
      at callback (node_modules\grpc\src\client_interceptors.js:841:24)



npm ERR! Test failed.  See above for more details.

**Comment by ryanpbrewster** [comment]
There is not enough information to diagnose this issue. It's possible the Firestore emulator was not running during your test (which would explain the `UNAVAILABLE` error).

Closing this issue out. Feel free to re-open if you are still running into this.
