### ISSUE TITLE
Firestore emulator doesn't work on CI

### ISSUE THREAD

**Issue by abraham** [firebase/quickstart-nodejs#48]
I checked out the [TypeScript sample](https://github.com/firebase/quickstart-nodejs/tree/master/firestore-emulator/typescript-quickstart) and that installs and runs fine locally. I can't get the tests to run on Travis CI or CircleCI though. I've created a [sample repo with basic configs](https://github.com/abraham/firestore-quickstart/pull/1) for both CI services.

- [Travis failed build](https://travis-ci.org/abraham/firestore-quickstart/builds/476141194)
- [Circle failed build](https://circleci.com/gh/abraham/firestore-quickstart/7)

I would think that running Firestore rule tests on CI would be very common and should work out of the box.

**Comment by samtstern** [comment]
Hmmm the error is pretty strange:

```
⚠  firestore: Error: Invalid or corrupt jarfile /home/travis/.cache/firebase/emulators/cloud-firestore-emulator-v1.2.2.jar
```

In the firebase/snippets-rules repo we run the emulator on CI successfully:
https://github.com/firebase/snippets-rules/blob/master/build.sh

@ryanpbrewster is there a possible problem with the latest emulator `jar`?

**Comment by ryanpbrewster** [comment]
I believe this is caused by a failed download. I think https://github.com/firebase/firebase-tools/pull/1097 should help with this.

**Comment by ryanpbrewster** [comment]
The error in your Circle logs is confusing to me:
```
firestore: Caused by: java.net.SocketException: Protocol family unavailable
```

The emulator is trying to bind `[::1]:8080` and `127.0.0.1:8080` by default. I'm not familiar with Circle, is it possible that they do not support both ipv4 and ipv6 transports?

**Comment by danahartweg** [comment]
I've run into the same issue in a Docker container in GitLab's CI (and local runner) environment.

Toggling the jvm option `-Djava.net.preferIPv4Stack=true` doesn't look to force things to behave correctly either. I'm going to keep exploring options, but it looks like the emulator (or underlying server library) should check for IPv6 support before binding.

**Comment by ryanpbrewster** [comment]
For the "Protocol family unavailable" error, you may want to explicitly set the host for the emulator via `--host=127.0.0.1`. The default is to bind both ipv4 and ipv6. There isn't yet an easy way to do this if you're running the emulator using `firebase serve --only firestore`, so for now you'll have to run the JAR directly.

The corrupt jarfile issue is interesting. I had hoped that v6.3.0 would fix this issue, but there must be something else going on. Is this issue reproducible? Or does it happen on some small % of CI runs?

**Comment by danahartweg** [comment]
Ahhh, I looked over and over again for hooks into `firebase-tools` that would allow specifying the port, and I wasn't able to find any. Great idea on running the `jar` directly!

Some additional updates after putting together a bash script:
+ Local CI Docker runs are successful!
+ Server CI Docker runs are also successful!
  + I moved `firebase setup:emulators:firestore` out of a `postinstall` and into the aforementioned bash script... something about the server CI environment must have been limiting things during `postinstall`, either permissions or timeouts or something (as it passed on the local Docker runs)
  + Not that it matters since it passed, but the `1.3.0` emulator reported as `67825938 bytes` with an md5 of `4703fa3f15b00a6a3330ab2b10bfbb4b`

Thanks for your direction @ryanpbrewster !

**Comment by danahartweg** [comment]
@abraham I plan to write up a little something about these workarounds (until there's something official in `firebase-tools` to connect to a specific port).

In the meantime, here's the bash script I threw together that you can use as a reference: https://gist.github.com/danahartweg/72600e0d30ae54290bf4deb197400ee9

**Comment by danahartweg** [comment]
Go right ahead! Definitely take them with a grain of salt, though, it's likely random or I just got lucky... especially with the emulator download =)

**Comment by danahartweg** [comment]
I've updated the above gist to include some process cleanup.

There ended up being issues in the old script with subsequent CI runs not allowing the emulator to start up because the previous process was still attached.

**Comment by wombat9000** [comment]
Hi! After reading this thread and following it's suggestions, I am still unable to get the emulator to reliably run in Gitlab CI. At this point, it has failed 5 out of 6 times. However, when I added statements to print out checksum and size, I got a single successful run, though it failed again on the next run.

The Error that keeps recurring:
```Error: Invalid or corrupt jarfile /root/.cache/firebase/emulators/cloud-firestore-emulator-v1.3.0.jar```

Build is running in a node11-alpine docker container with openjdk-8 installed. It works fine when running the emulator from within the container locally. I have not tried it with other CI providers.

firebase-tools: 6.3.1
openjdk: 1.8.0_191

I'm running the emulator using
```$ java -jar $HOME/.cache/firebase/emulators/cloud-firestore-emulator-v1.3.0.jar --host=127.0.0.1```

Checksum and sizes:
```
// successful run:
md5: 4703fa3f15b00a6a3330ab2b10bfbb4b
size: 67.825.938 

// failed run, note the smaller size:
md5: 294578237bd73ef4de1c221675d4ab76
size: 67.821.568 
```

Any ideas what might cause the download to (silently) fail in this manner?

Thanks for your time!

**Comment by ryanpbrewster** [comment]
No clue. I've opened https://github.com/firebase/firebase-tools/pull/1144 to add more validation to the download.

Right now we're downloading to a tempfile like `/tmp/xyz`, then copying it to `$HOME/.cache/firebase/emulators/${name}`. I'm wondering if perhaps your docker environment has limits on disk space such that copying around a 60+ MB file is an issue. Do you happen to have any logs or further details on the runs that have a corrupted JAR-file?

**Comment by wombat9000** [comment]
Gitlab: https://docs.gitlab.com/ce/user/gitlab_com/#shared-runners

> All your CI/CD jobs run on n1-standard-1 instances with 3.75GB of RAM, CoreOS and the latest Docker Engine installed. Instances provide 1 vCPU and 25GB of HDD disk space. The default region of the VMs is US East1. Each instance is used only for one job, this ensures any sensitive data left on the system can’t be accessed by other people their CI jobs.

Going by this, I'd guess filesize is not the issue? Afaik the network is somewhat slow though...

I setup a minimal-repo to easiert reproduce this issue, here the logoutput of the most recent failure:
https://gitlab.com/wombat9000/firestore-emulator-ci/-/jobs/160632820

In the repo, you can also find the dockerfile of the image used to perform the build.

**Comment by ryanpbrewster** [comment]
I'll try to reproduce this on my end.

As an aside, I see that in your repo you are building a base image that has `firebase-tools` installed, but you're downloading the emulator in the `gitlab-ci.yml`. Could you add
```
RUN firebase setup:emulators:firestore
```
to your Dockerfile so that it doesn't get downloaded during the CI run?

**Comment by wombat9000** [comment]
Ah thanks for pointing that out. It does make a lot more sense to verify the download when building the image, and then being able to rely on it in CI. 
From the most recent [build-log](https://gitlab.com/wombat9000/firestore-emulator-ci/-/jobs/161120981) you can see that did the trick.

Cheers!

**Comment by ryanpbrewster** [comment]
Awesome, glad that helped :)

**Comment by elvisun** [comment]
For those who find this thread through google, like others have suggested, you may need to explicitly set the host for the emulator as `127.0.0.1`.

I got it to work on CircleCI by adding this to `firebase.json`
```
{
  ...
  },
  "emulators": {
    "functions": {
      "port": 5001,
      "host": "127.0.0.1"
    },
    "firestore": {
      "port": 8080,
      "host": "127.0.0.1"
    },
    "database": {
      "port": 9000,
      "host": "127.0.0.1"
    },
    "hosting": {
      "port": 5000,
      "host": "127.0.0.1"
    }
  }
}
```
and adding `process.env.FIRESTORE_EMULATOR_HOST = "127.0.0.1:8080";` in my tests
