### ISSUE TITLE
can I simply connect to emulator in my webapp while developing

### ISSUE THREAD

**Issue by arashbi** [firebase/quickstart-nodejs#54]
Sorry guys,  I know this is not the place to ask this question. But unfortunately the documentation is very incomplete.
How can I connect to a running emulator from my application?

**Comment by samtstern** [comment]
@arashbi this is something we're working on but have not finished.  Right now the emulator can only be used for unit testing, as you see in this repo.

The emulators are fully capable Firestore/RTDB backends but we need to add support in the Client SDKs for talking to them.
