### ISSUE TITLE
Surpress firestore output

### ISSUE THREAD

**Issue by jvanderen1** [firebase/quickstart-nodejs#56]
I was wondering if there would be a way to surpress logs from the firestore emulator? I would like to use [start-server-and-test](https://www.npmjs.com/package/start-server-and-test/v/1.7.6) to test `firestore rules`, but the output gets cluttered from both the emulator and test bench.

**Comment by ryanpbrewster** [comment]
I'm not very familiar with start-server-and-test, but it looks like it takes a shell command to start the server. Can you add a redirect in there? Something like
```
{
    "scripts": {
        "start-server": "firebase serve --only firestore > /dev/null",
        "test": "mocha e2e-spec.js",
        "ci": "start-server-and-test start-server http://localhost:8080 test"
    }
}
```

**Comment by jvanderen1** [comment]
Yes, that does the trick. Thanks a bunch! 👍
