### ISSUE TITLE
Does Firebase Admin SDK support Firestore Emulator?

### ISSUE THREAD

**Issue by caiorcferreira** [firebase/quickstart-nodejs#59]
I'm trying to set up a local environment running with the Firestore Emulator and Node.js but when I ran my script it wrote the data to the hosted Firestore instead of the local one.

I'm using the "Initialize in your own server" setup described [here](https://firebase.google.com/docs/firestore/quickstart) and setting `export FIRESTORE_EMULATOR_HOST=[::1]:8080,127.0.0.1:8080` on my terminal.

Am I doing something wrong or this simply doesn't have support?

Thanks

**Comment by samtstern** [comment]
@caiorcferreira sorry for the slow response here.  If you use the google-cloud Firestore lib directly you can talk to the emulator:

```
import { Firestore } from '@google-cloud/firestore';
import { credentials } from 'grpc';

const firestore = new Firestore({
  port: 8080,
  projectId: 'YOUR_PROJECT_ID',
  servicePath: 'localhost',
  sslCreds: credentials.createInsecure(),
});
```

Hope that helps!  I am going to close this here and file a new issue on the Admin SDK about detecting the environment variable.

**Comment by shkreza** [comment]
@samtstern , this was helpful but one more question - how do you add auth (auth.uid, specifically) to the firestore object. Without it all my firestore security rules that refer to request.auth.uid break!

**Comment by ryanpbrewster** [comment]
As of the most recent release (https://github.com/googleapis/nodejs-firestore/releases/tag/v2.1.0) you set custom headers like so:
```
const firestore = new Firestore({
  projectId: 'firestore-emulator-sample',
  servicePath: 'localhost',
  port: 8080,
  sslCreds: grpc.credentials.createInsecure(),
  customHeaders: {
    "Authorization": "Bearer owner"
  }
});
```

The Firestore emulator accepts this `"Bearer owner"` authorization header and will treat the SDK connection as an admin.

**Comment by shkreza** [comment]
@ryanpbrewster, this is exactly what I was looking for and it was very timely.. thanks!

I also need to do array set/merge as part of my testing - when I add the `arrayUnion()` call, I get an error (see below). The same code without `FieldValue.arrayUnion` call does not produce any errors.

**Code:**
```javascript
import { Firestore, FieldValue } from '@google-cloud/firestore';
...
firestore
  .collection(_COLLECTION_KEYS.USERS)
  .doc(requesteeId)
  .set({
    friendRequests: FieldValue.arrayUnion([requesterId])
  }, {
    merge: true
  })
```

**Error:**
```
  at Http2CallStream.<anonymous> (firestore/functions/node_modules/@grpc/grpc-js/build/src/client.js:102:45)
  at Http2CallStream.endCall (firestore/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:74:18)
  at firestore/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:163:18
  at firestore/functions/node_modules/@grpc/grpc-js/build/src/call-stream.js:354:13
```

And a **Warning:**
```
  console.warn node_modules/@firebase/util/dist/index.node.cjs.js:656
  Overwriting FirebaseError base field "name" can cause unexpected behavior.
```

**Package versions:**
* "@grpc/grpc-js@0.4.0"
* "@google-cloud/firestore": "^2.1.1",
* "@firebase/util@0.2.17"
* "firebase-admin": "^8.0.0",
* "firebase-functions": "^2.3.1"

**Comment by explunit** [comment]
Note for anyone else who tries to use the sample code in this issue:

You have to use `grpc-js` instead of `grpc` https://stackoverflow.com/questions/60358056/error-passing-empty-credentials-to-firestore-emulator
