### ISSUE TITLE
package.json "test" script for firestone emulator

### ISSUE THREAD

**Issue by Orest-Cokan** [firebase/quickstart-nodejs#61]
I keep getting thrown this error upon typing in npm test

'FIREBASE_FIRESTORE_EMULATOR_ADDRESS' is not recognized as an internal or external command,

**Comment by xTaz1** [comment]
Do you use Windows ?

**Comment by ryanpbrewster** [comment]
This has been removed from the quickstarts and should no longer be an issue.

FWIW, `VARIABLE="some value" npm test` is a legal way to set environment variables on Unix systems. If you're on another system that may have caused problems.
