### ISSUE TITLE
RTDB Trigger functions not being called

### ISSUE THREAD

**Issue by grennis** [firebase/quickstart-nodejs#77]
Hi,
I saw in the release 7.0.0 of the tools that RTDB triggers should now be supported (https://github.com/firebase/firebase-tools/releases/tag/v7.0.0)

I saw when starting the emulators, that it did print out `i  functions: Setting up Realtime Database trigger "myTriggerName"`

But, when inserting data into the realtime DB, the trigger function is never called. When I run using a real/remote firebase instance, it works.

Should I expect this to be working yet?

**Comment by samtstern** [comment]
Can you show the code you're using to connect to the RTDB emulator and
write?  Also can you show the function trigger definition you expect to
match?

**Comment by grennis** [comment]
Sounds like it should be working then. I'll see if I can put together a straightforward example to reproduce the issue.

**Comment by samtstern** [comment]
We're fixing this now, so no reproduction needed.  I got one on my side.
Thanks for reporting!

**Comment by grennis** [comment]
Great news thanks!
