### ISSUE TITLE
firestore emulator in javascript quickstart won't start

### ISSUE THREAD

**Issue by forrestswork** [firebase/quickstart-nodejs#78]
i was not able to run the quickstart test until i ran `firebase init`

**Comment by Crowbrammer** [comment]
Firebase requires project (and port) access. Project (and port) setup need to be done before the emulation and testing can begin. These steps aren't but should be in the documentation. Might submit a PR for the docs once I get this working.

**Comment by samtstern** [comment]
@forrestswork the latest version of the Firebase CLI (`firebase-tools`) no longer requires a project to run the Firestore emulator.
