### ISSUE TITLE
What is options in initializeApp

### ISSUE THREAD

**Issue by ivawzh** [firebase/quickstart-nodejs#8]
Your [documentation](https://firebase.google.com/docs/reference/js/firebase.app.App.html#options) does not say for [`firebase.initializeApp(options, name)`](https://firebase.google.com/docs/reference/js/firebase.html#.initializeApp) what the supported options are.

**Comment by nicolasgarnier** [comment]
@ivawzh We're updating the reference docs to add a sample, sorry about that. In the mean time please have a look at this page: 

https://firebase.google.com/docs/server/setup
