### ISSUE TITLE
Doc update: Connecting a project

### ISSUE THREAD

**Issue by Crowbrammer** [firebase/quickstart-nodejs#83]
Required but missing from [the quickstart doc](https://github.com/firebase/quickstart-nodejs/tree/master/firestore-emulator/javascript-quickstart):

**Comment by samtstern** [comment]
@Crowbrammer do you mean running `firebase init`?  If so I believe you fixed this with #85, right?

**Comment by Crowbrammer** [comment]
@samtstern I believe so, too!
